# Generated by Django 2.2 on 2020-10-21 11:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todoList', '0004_userfollowing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFollowing',
            new_name='UserContacts',
        ),
    ]
